### ISSUE TITLE
[Git Action] Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by Yeonji-Lim** [mermaid-pirates/WAIS#12]
## 문제 상황

PR 생성 후 오류 발생

https://github.com/mermaid-pirates/WAIS/pull/11#issue-1310308217

<img width="925" alt="image" src="https://user-images.githubusercontent.com/57888020/179883390-097676fa-5349-4d4f-aca8-25de384dc42a.png">

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/57888020/179883088-41aebee4-bca6-49bf-9428-a8e7d594e02f.png">

**Comment by Yeonji-Lim** [comment]
해당 PR의 commit 515a06159daa2a35f520d591810051283df795d7 에서 발생

**Comment by seungy0** [comment]
PR 시 Action 동작안하게 수정 완료
