### ISSUE TITLE
[Git Action] ERROR : Process completed with exit code 128

### ISSUE THREAD

**Issue by Yeonji-Lim** [mermaid-pirates/WAIS#5]
# 문제 상황

https://github.com/mermaid-pirates/WAIS/commits/main

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/57888020/179357241-7e1216d1-fa38-4e84-a0a3-db39f94958c7.png">

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/57888020/179357271-a3a5f230-faf0-4f05-9ccc-d17a926620bb.png">

subtree 관련

**Comment by seungy0** [comment]
@hyh1016 
정확힌 모르겠는데 organization 관리자가 토큰 인증 허용해주면 해결될거 같음.

**Comment by hyh1016** [comment]
@seungy0 
Secret -> Action에 환경 변수로 등록해주면 되는데, 팀원 전원 Admin으로 설정했기 때문에 아무나 등록할 수 있을 겁니다.
안 되면 개인 톡으로 토큰 넘겨 주세요. 👍

**Comment by seungy0** [comment]
@hyh1016 
ㄴㄴ 나는 관리 권한 없음. 내 토큰을 주는게 아니라 네가 new organization secret 만들어야 될걸

**Comment by seungy0** [comment]
7/19 해결.
